Main script

loadstring(game:HttpGet("https://raw.githubusercontent.com/localplayerr/Doors-stuff/refs/heads/main/Hardcore%20v4%20recreate/main%20code"))()

# Supported executors:

delta
wave
seliware
synapse z
awp
Zorara
# Supported executors but version will be a little bad

solara
xeno

# Unsupported executors:

swift
fluxteam
Also some executors may not be listed here but still may work if it does good for you 
